Repository PeopleForBikes/bna-api, pull requests merged in 2024-10, with the labels that each got.

#146 fix(codegen) OpenAPI now works with `cargo-progenitor`
  openapi.yaml
Labels: size/S

#148 Refactor endpoints
  .gitignore
  Cargo.toml
  effortless/Cargo.toml
  effortless/src/api.rs
  effortless/src/error.rs
  effortless/src/fragment.rs
  examples/seeder.rs
  lambdas/Cargo.toml
  lambdas/src/bin/cities/get-cities-census.rs
  lambdas/src/bin/cities/get-cities-ratings.rs
  lambdas/src/bin/cities/get-cities-submissions.rs
  lambdas/src/bin/cities/get-cities.rs
  lambdas/src/bin/cities/patch-cities-submissions.rs
  lambdas/src/bin/cities/post-cities-submissions.rs
  lambdas/src/bin/cities/post-cities.rs
  lambdas/src/bin/price-fargate/get-price-fargate.rs
  lambdas/src/bin/ratings/get-ratings-analysis.rs
  lambdas/src/bin/ratings/get-ratings-cities.rs
  lambdas/src/bin/ratings/get-ratings-results.rs
  lambdas/src/bin/ratings/get-ratings.rs
  lambdas/src/bin/ratings/patch-ratings-analysis.rs
  lambdas/src/bin/ratings/patch-ratings.rs
  lambdas/src/bin/ratings/post-ratings-analysis.rs
  lambdas/src/bin/ratings/post-ratings-enqueue.rs
  lambdas/src/bin/ratings/post-ratings.rs
  lambdas/src/cities/get-cities-submissions.rs
  lambdas/src/cities/patch-cities-submissions.rs
  lambdas/src/cities/post-cities.rs
  lambdas/src/core/link_header.rs
  lambdas/src/core/mod.rs
  lambdas/src/core/resource/cities/adaptor.rs
  lambdas/src/core/resource/cities/db.rs
  lambdas/src/core/resource/cities/endpoint.rs
  lambdas/src/core/resource/cities/mod.rs
  lambdas/src/core/resource/mod.rs
  lambdas/src/core/resource/price/adaptor.rs
  lambdas/src/core/resource/price/db.rs
  lambdas/src/core/resource/price/endpoint.rs
  lambdas/src/core/resource/price/mod.rs
  lambdas/src/core/resource/ratings/adaptor.rs
  lambdas/src/core/resource/ratings/db.rs
  lambdas/src/core/resource/ratings/endpoint.rs
  lambdas/src/core/resource/ratings/mod.rs
  lambdas/src/db.rs
  lambdas/src/lib.rs
  lambdas/src/main.rs
  lambdas/src/ratings/get-ratings-analysis.rs
  lambdas/src/ratings/patch-ratings-analysis.rs
  lambdas/tests/endpoints/cities.hurl
  lambdas/tests/endpoints/ratings.hurl
  lambdas/tests/justfile
  lambdas/tests/localhost.vars
  lambdas/tests/requirements.txt
  lambdas/tests/scenario/pagination.hurl
  lambdas/tests/smoke/public-readonly.hurl
  migration/src/m20240202_004130_brokenspoke_analyzer_pipeline.rs
Labels: size/XXL

#149 Fix ratings endpoint
  examples/seeder.rs
  lambdas/src/bin/ratings/get-ratings.rs
Labels: size/XS

#150 Fix POST submission endpoint
  lambdas/src/bin/cities/post-cities-submissions.rs
Labels: size/XS

#151 Fix price endpoint
  examples/seeder.rs
  lambdas/src/bin/price-fargate/get-price-fargate.rs
  lambdas/src/core/resource/price/mod.rs
  lambdas/src/lib.rs
Labels: size/L

#152 Rename Path parameters
  effortless/src/api.rs
  lambdas/requests.rest
  lambdas/src/bin/price-fargate/get-price-fargate.rs
  lambdas/src/bin/ratings/get-ratings-analysis.rs
  lambdas/src/bin/ratings/get-ratings-cities.rs
  lambdas/src/bin/ratings/get-ratings.rs
  lambdas/src/core/resource/price/endpoint.rs
  lambdas/src/core/resource/ratings/db.rs
  lambdas/src/core/resource/ratings/endpoint.rs
  lambdas/src/core/resource/ratings/mod.rs
  lambdas/src/fixtures/get-bnas-bna_id.json
  lambdas/src/fixtures/get-cities-bnas-bna_id.json
  lambdas/tests/endpoints/ratings.hurl
  lambdas/tests/localhost.vars
  lambdas/tests/smoke/public-readonly.hurl
  lambdas/tests/staging.vars
  openapi.yaml
Labels: size/L
